spring:
  application:
    name: insu

  datasource:
    url: jdbc:oracle:thin:@localhost:15210/XEPDB1
    username: ${DB_USERNAME:insurance}
    password: ${DB_PASSWORD:1234}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  thymeleaf:
    cache: false

server:
  port: ${SERVER_PORT:8080}

gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com
  model: gemini-2.0-flash