-- Hama service/search schema extension
-- 202605 base schema keeps the product, user, wishlist, chatbot, and notification core.
-- This migration adds the tables needed for search events, match evidence, price statistics,
-- content pages, and richer ranking batches.

alter table public.wishlists
  add column if not exists is_sold_alert boolean not null default true;

alter table public.search_rankings
  add column if not exists platform_name text,
  add column if not exists period_start date,
  add column if not exists period_end date,
  add column if not exists calculated_at timestamptz not null default now();

alter table public.search_rankings
  drop constraint if exists search_rankings_keyword_key;

create index if not exists idx_search_rankings_period
  on public.search_rankings (period_start desc, period_end desc, search_count desc);

create table if not exists public.search_events (
  event_id bigint generated by default as identity primary key,
  user_id uuid references public.users(user_id) on delete set null,
  keyword text not null,
  platform_name text,
  item_id bigint references public.items(item_id) on delete set null,
  event_type text not null check (event_type in ('SEARCH', 'IMPRESSION', 'CLICK')),
  result_rank integer check (result_rank is null or result_rank > 0),
  relevance_score numeric,
  query_source text,
  created_at timestamptz not null default now()
);

create index if not exists idx_search_events_keyword_created
  on public.search_events (keyword, created_at desc);

create index if not exists idx_search_events_user_created
  on public.search_events (user_id, created_at desc);

create index if not exists idx_search_events_item_created
  on public.search_events (item_id, created_at desc);

create table if not exists public.item_search_matches (
  match_id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(item_id) on delete cascade,
  keyword text not null,
  canonical_name text,
  match_score numeric,
  match_reason text,
  match_source text not null default 'batch',
  matched_at timestamptz not null default now(),
  constraint uq_item_search_matches_item_keyword unique (item_id, keyword)
);

create index if not exists idx_item_search_matches_keyword_score
  on public.item_search_matches (keyword, match_score desc);

create table if not exists public.price_stats_daily (
  stat_id bigint generated by default as identity primary key,
  canonical_name text not null,
  platform_name text,
  stat_date date not null,
  lowest_price integer check (lowest_price is null or lowest_price >= 0),
  average_price numeric check (average_price is null or average_price >= 0),
  item_count integer not null default 0 check (item_count >= 0),
  calculated_at timestamptz not null default now(),
  constraint uq_price_stats_daily unique (canonical_name, platform_name, stat_date)
);

create index if not exists idx_price_stats_daily_name_date
  on public.price_stats_daily (canonical_name, stat_date desc);

create table if not exists public.content_pages (
  content_id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('NOTICE', 'TERMS', 'PRIVACY', 'FAQ', 'GUIDE')),
  title text not null,
  body text not null,
  version text,
  is_active boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_content_pages_type_active
  on public.content_pages (content_type, is_active, published_at desc);

alter table public.search_events enable row level security;
alter table public.item_search_matches enable row level security;
alter table public.price_stats_daily enable row level security;
alter table public.content_pages enable row level security;

drop policy if exists "users insert own search events" on public.search_events;
create policy "users insert own search events" on public.search_events
  for insert to authenticated
  with check ((user_id is null) or ((select auth.uid()) = user_id));

drop policy if exists "public read price stats daily" on public.price_stats_daily;
create policy "public read price stats daily" on public.price_stats_daily
  for select using (true);

drop policy if exists "public read active content pages" on public.content_pages;
create policy "public read active content pages" on public.content_pages
  for select using (is_active = true);
