-- Hama DB 스키마 (PostgreSQL / Supabase)
-- 2026-06-12 라이브 DB(kgpkcvuawbpgdcyykfdk) 기준 덤프 정리본.
-- 실제 적용 이력은 code/supabase/migrations/*.sql 참고.
-- ERD: docs/db_erd.md

-- ============================================================
-- 시퀀스 (Spring JPA 엔티티가 사용하는 수동 시퀀스)
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS user_seq;
CREATE SEQUENCE IF NOT EXISTS wishlist_seq;
CREATE SEQUENCE IF NOT EXISTS notification_seq;
CREATE SEQUENCE IF NOT EXISTS notification_setting_seq;
CREATE SEQUENCE IF NOT EXISTS keyword_alert_seq;
CREATE SEQUENCE IF NOT EXISTS item_view_seq;
CREATE SEQUENCE IF NOT EXISTS search_log_seq;
CREATE SEQUENCE IF NOT EXISTS chat_history_seq;
CREATE SEQUENCE IF NOT EXISTS chat_faq_seq;
CREATE SEQUENCE IF NOT EXISTS recommended_items_seq;

-- ============================================================
-- 1. 사용자
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    user_id             BIGINT PRIMARY KEY DEFAULT nextval('user_seq'),
    login_id            VARCHAR UNIQUE NOT NULL,
    email               VARCHAR UNIQUE NOT NULL,
    password            VARCHAR NOT NULL,
    name                VARCHAR NOT NULL,
    birth_date          DATE,
    nickname            VARCHAR UNIQUE NOT NULL,
    privacy_agreed_at   TIMESTAMP NOT NULL DEFAULT now(),
    marketing_agreed_at TIMESTAMP,
    account_status      VARCHAR NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE | WITHDRAWN (탈퇴는 soft delete)
    role                VARCHAR NOT NULL DEFAULT 'USER',     -- USER | ADMIN (관리자 페이지 가드)
    created_at          TIMESTAMP NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notification_settings (
    setting_id           BIGINT PRIMARY KEY DEFAULT nextval('notification_setting_seq'),
    user_id              BIGINT UNIQUE NOT NULL REFERENCES users(user_id),
    lowest_price_enabled VARCHAR NOT NULL DEFAULT 'Y',
    sold_status_enabled  VARCHAR NOT NULL DEFAULT 'Y',
    new_item_enabled     VARCHAR NOT NULL DEFAULT 'Y',
    updated_at           TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS keyword_alerts (
    keyword_alert_id BIGINT PRIMARY KEY DEFAULT nextval('keyword_alert_seq'),
    user_id          BIGINT NOT NULL REFERENCES users(user_id),
    keyword          VARCHAR NOT NULL,
    is_active        VARCHAR NOT NULL DEFAULT 'Y',
    created_at       TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_preferences (
    pref_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    preferred_tag TEXT NOT NULL
);

-- ============================================================
-- 2. 매물
-- ============================================================
CREATE TABLE IF NOT EXISTS platforms (
    platform_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_name TEXT UNIQUE NOT NULL,        -- 번개장터 | 중고나라
    is_active     BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS items (
    item_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id          BIGINT REFERENCES platforms(platform_id),
    platform_name        TEXT,                 -- 비정규화 컬럼 (트리거로 platform_id와 동기화)
    original_id          TEXT NOT NULL,        -- 플랫폼별 상품 ID(pid)
    canonical_name       TEXT NOT NULL,        -- 표준 상품명 (검색/집계 기준)
    cluster_product_name TEXT,                 -- 클러스터 표준 상품명 (파생, keyword_final 파이프라인)
    title                TEXT NOT NULL,
    current_price        INTEGER NOT NULL CHECK (current_price >= 0),
    lowest_price         INTEGER CHECK (lowest_price IS NULL OR lowest_price >= 0),
    status               TEXT NOT NULL DEFAULT '판매중',   -- 판매중 | 예약중 | 판매완료
    description          TEXT,
    category_name        TEXT,
    matched_keywords     TEXT,
    thumbnail_url        TEXT,
    item_url             TEXT NOT NULL,
    rating               NUMERIC,              -- 종합 점수 (cluster/price/view/recency 가중합)
    cluster_score        NUMERIC,
    price_score          NUMERIC,
    view_score           NUMERIC,
    recency_score        NUMERIC,
    cluster_confidence   NUMERIC,              -- 클러스터 신뢰도 (관리자 이상데이터 기준)
    view_count           INTEGER NOT NULL DEFAULT 0,
    crawled_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    sold_at              TIMESTAMPTZ,
    url_checked_at       TIMESTAMPTZ,
    url_status           TEXT,
    last_seen_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS price_history (
    history_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id     BIGINT NOT NULL REFERENCES items(item_id),
    price       INTEGER NOT NULL CHECK (price >= 0),
    recorded_at DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS item_search_matches (
    match_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id        BIGINT NOT NULL REFERENCES items(item_id),
    keyword        TEXT NOT NULL,
    canonical_name TEXT,
    match_score    NUMERIC,
    match_reason   TEXT,
    match_source   TEXT NOT NULL DEFAULT 'batch',
    matched_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 3. 시세 집계
-- ============================================================
CREATE TABLE IF NOT EXISTS price_stats_daily (
    stat_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    platform_name  TEXT,
    stat_date      DATE NOT NULL,
    lowest_price   INTEGER CHECK (lowest_price IS NULL OR lowest_price >= 0),
    average_price  NUMERIC CHECK (average_price IS NULL OR average_price >= 0),
    item_count     INTEGER NOT NULL DEFAULT 0 CHECK (item_count >= 0),
    calculated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS keyword_price_daily (
    trend_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword       TEXT NOT NULL,
    recorded_at   DATE NOT NULL,
    lowest_price  INTEGER NOT NULL CHECK (lowest_price >= 0),
    average_price INTEGER NOT NULL CHECK (average_price >= 0),
    sample_count  INTEGER NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS search_rankings (
    rank_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword       TEXT NOT NULL,
    search_count  INTEGER NOT NULL DEFAULT 0,
    trend_status  TEXT,
    platform_name TEXT,
    period_start  DATE,
    period_end    DATE,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 4. 사용자 활동
-- ============================================================
CREATE TABLE IF NOT EXISTS wishlists (
    wish_id         BIGINT PRIMARY KEY DEFAULT nextval('wishlist_seq'),
    user_id         BIGINT NOT NULL REFERENCES users(user_id),
    item_id         BIGINT NOT NULL REFERENCES items(item_id),
    target_price    BIGINT CHECK (target_price IS NULL OR target_price >= 0),
    is_lowest_alert VARCHAR NOT NULL DEFAULT 'Y',
    added_at        TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS item_views (
    view_id   BIGINT PRIMARY KEY DEFAULT nextval('item_view_seq'),
    user_id   BIGINT NOT NULL REFERENCES users(user_id),
    item_id   BIGINT NOT NULL REFERENCES items(item_id),
    viewed_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS search_logs (
    log_id          BIGINT PRIMARY KEY DEFAULT nextval('search_log_seq'),
    user_id         BIGINT REFERENCES users(user_id),
    keyword         VARCHAR NOT NULL,
    clicked_item_id BIGINT REFERENCES items(item_id),
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS search_events (
    event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES users(user_id),
    keyword         TEXT NOT NULL,
    platform_name   TEXT,
    item_id         BIGINT REFERENCES items(item_id),
    event_type      TEXT NOT NULL CHECK (event_type IN ('SEARCH', 'IMPRESSION', 'CLICK')),
    result_rank     INTEGER CHECK (result_rank IS NULL OR result_rank > 0),
    relevance_score NUMERIC,
    query_source    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recommended_items (
    recommend_id   BIGINT PRIMARY KEY DEFAULT nextval('recommended_items_seq'),
    user_id        BIGINT NOT NULL REFERENCES users(user_id),
    item_id        BIGINT NOT NULL REFERENCES items(item_id),
    score          INTEGER,
    recommend_type VARCHAR,                    -- 예: CHATBOT_RECOMMEND
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id   BIGINT PRIMARY KEY DEFAULT nextval('notification_seq'),
    user_id           BIGINT NOT NULL REFERENCES users(user_id),
    item_id           BIGINT REFERENCES items(item_id),
    notification_type VARCHAR NOT NULL,
    title             VARCHAR NOT NULL,
    message           VARCHAR,
    payload           TEXT,
    is_read           VARCHAR NOT NULL DEFAULT 'N',
    send_status       VARCHAR NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    sent_at           TIMESTAMP,
    read_at           TIMESTAMP
);

-- ============================================================
-- 5. 챗봇
-- ============================================================
CREATE TABLE IF NOT EXISTS chat_history (
    chat_id       BIGINT PRIMARY KEY DEFAULT nextval('chat_history_seq'),
    user_id       BIGINT REFERENCES users(user_id),
    user_message  TEXT,
    bot_response  TEXT,
    intent        VARCHAR,
    response_type VARCHAR,
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_faq (
    faq_id           BIGINT PRIMARY KEY DEFAULT nextval('chat_faq_seq'),
    question_pattern TEXT,
    answer_text      TEXT
);

-- ============================================================
-- 6. 콘텐츠/운영
-- ============================================================
CREATE TABLE IF NOT EXISTS content_pages (
    content_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type TEXT NOT NULL CHECK (content_type IN ('NOTICE', 'TERMS', 'PRIVACY', 'FAQ', 'GUIDE')),
    title        TEXT NOT NULL,
    body         TEXT NOT NULL,
    version      TEXT,
    is_active    BOOLEAN NOT NULL DEFAULT true,
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS banners (
    banner_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url     TEXT NOT NULL,
    link_url      TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true
);
