-- Hama MVP Supabase/Postgres schema
-- docs/db_schema.sql의 Oracle 문법을 Supabase(Postgres) 기준으로 변환한 버전입니다.

create table if not exists public.platforms (
  platform_id bigint generated by default as identity primary key,
  platform_name text not null unique
);

create table if not exists public.items (
  item_id bigint generated by default as identity primary key,
  platform_id bigint not null references public.platforms(platform_id),
  original_id text not null,
  canonical_name text not null,
  title text not null,
  current_price integer not null check (current_price >= 0),
  lowest_price integer check (lowest_price is null or lowest_price >= 0),
  status text not null default '판매중',
  description text,
  category_name text,
  matched_keywords text,
  thumbnail_url text,
  item_url text not null,
  crawled_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_items_platform_original unique (platform_id, original_id)
);

create index if not exists idx_items_canonical_name on public.items (canonical_name);
create index if not exists idx_items_platform_id on public.items (platform_id);
create index if not exists idx_items_crawled_at on public.items (crawled_at desc);

create table if not exists public.price_history (
  history_id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(item_id) on delete cascade,
  price integer not null check (price >= 0),
  recorded_at date not null default current_date,
  created_at timestamptz not null default now(),
  constraint uq_price_history_item_date unique (item_id, recorded_at)
);

create index if not exists idx_price_history_item_date
  on public.price_history (item_id, recorded_at);

create table if not exists public.wishlists (
  wish_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.items(item_id) on delete cascade,
  target_price integer check (target_price is null or target_price >= 0),
  is_lowest_alert boolean not null default true,
  added_at timestamptz not null default now(),
  constraint uq_wishlists_user_item unique (user_id, item_id)
);

create table if not exists public.search_logs (
  log_id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  keyword text not null,
  clicked_item_id bigint references public.items(item_id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.search_rankings (
  rank_id bigint generated by default as identity primary key,
  keyword text not null unique,
  search_count integer not null default 0,
  trend_status text,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  pref_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  preferred_tag text not null,
  constraint uq_user_preferences_user_tag unique (user_id, preferred_tag)
);

create table if not exists public.banners (
  banner_id bigint generated by default as identity primary key,
  image_url text not null,
  link_url text,
  display_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.chat_history (
  chat_id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_message text,
  bot_response text,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_faq (
  faq_id bigint generated by default as identity primary key,
  question_pattern text,
  answer_text text
);

create table if not exists public.recommended_items (
  recommend_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.items(item_id) on delete cascade,
  score numeric,
  recommend_type text,
  created_at timestamptz not null default now()
);

alter table public.platforms enable row level security;
alter table public.items enable row level security;
alter table public.price_history enable row level security;
alter table public.wishlists enable row level security;
alter table public.search_logs enable row level security;
alter table public.search_rankings enable row level security;
alter table public.user_preferences enable row level security;
alter table public.banners enable row level security;
alter table public.chat_history enable row level security;
alter table public.chat_faq enable row level security;
alter table public.recommended_items enable row level security;

drop policy if exists "public read platforms" on public.platforms;
create policy "public read platforms" on public.platforms
  for select using (true);

drop policy if exists "public read items" on public.items;
create policy "public read items" on public.items
  for select using (true);

drop policy if exists "public read price history" on public.price_history;
create policy "public read price history" on public.price_history
  for select using (true);

drop policy if exists "public read rankings" on public.search_rankings;
create policy "public read rankings" on public.search_rankings
  for select using (true);

drop policy if exists "public read active banners" on public.banners;
create policy "public read active banners" on public.banners
  for select using (is_active = true);

drop policy if exists "users read own wishlists" on public.wishlists;
create policy "users read own wishlists" on public.wishlists
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own wishlists" on public.wishlists;
create policy "users manage own wishlists" on public.wishlists
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own preferences" on public.user_preferences;
create policy "users read own preferences" on public.user_preferences
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own preferences" on public.user_preferences;
create policy "users manage own preferences" on public.user_preferences
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own chat history" on public.chat_history;
create policy "users read own chat history" on public.chat_history
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users insert own search logs" on public.search_logs;
create policy "users insert own search logs" on public.search_logs
  for insert to authenticated with check ((select auth.uid()) = user_id);
