-- Hama Supabase/Postgres schema
-- Supabase Auth(auth.users)를 메인 사용자 원본으로 두고, public.users는 앱 프로필로 사용합니다.
-- 실제 적용 기준 파일은 code/supabase/migrations/*.sql 입니다.

create table if not exists public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  login_id text unique,
  email text not null unique,
  name text not null,
  birth_date date,
  phone_number text,
  nickname text not null unique,
  role text not null default 'USER',
  privacy_agreed_at timestamptz not null default now(),
  marketing_agreed_at timestamptz,
  account_status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.items (
  item_id bigint generated by default as identity primary key,
  platform_name text not null,
  original_id text not null,
  canonical_name text not null,
  title text not null,
  current_price integer not null check (current_price >= 0),
  lowest_price integer check (lowest_price is null or lowest_price >= 0),
  status text not null default '판매중',
  sold_at timestamptz,
  description text,
  category_name text,
  matched_keywords text,
  thumbnail_url text,
  item_url text not null,
  url_checked_at timestamptz,
  url_status text,
  crawled_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  cluster_product_name text,
  cluster_confidence numeric(4, 2),
  cluster_score numeric(5, 2),
  price_score numeric(5, 2),
  view_score numeric(5, 2),
  recency_score numeric(5, 2),
  view_count integer not null default 0,
  rating numeric(6, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_items_platform_original unique (platform_name, original_id)
);

create index if not exists idx_items_canonical_name on public.items (canonical_name);
create index if not exists idx_items_platform_name on public.items (platform_name);
create index if not exists idx_items_crawled_at on public.items (crawled_at desc);
create index if not exists idx_items_status on public.items (status);
create index if not exists idx_items_rating_desc on public.items (rating desc);
create index if not exists idx_items_cluster_product_name on public.items (cluster_product_name);

create table if not exists public.price_history (
  history_id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(item_id) on delete cascade,
  price integer not null check (price >= 0),
  recorded_at date not null default current_date,
  created_at timestamptz not null default now(),
  constraint uq_price_history_item_date unique (item_id, recorded_at)
);

create index if not exists idx_price_history_item_date
  on public.price_history (item_id, recorded_at);

create table if not exists public.wishlists (
  wish_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  item_id bigint not null references public.items(item_id) on delete cascade,
  target_price integer check (target_price is null or target_price >= 0),
  is_lowest_alert boolean not null default true,
  added_at timestamptz not null default now(),
  constraint uq_wishlists_user_item unique (user_id, item_id)
);

create table if not exists public.search_logs (
  log_id bigint generated by default as identity primary key,
  user_id uuid references public.users(user_id) on delete set null,
  keyword text not null,
  clicked_item_id bigint references public.items(item_id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_search_logs_user_created
  on public.search_logs (user_id, created_at desc);

create table if not exists public.search_rankings (
  rank_id bigint generated by default as identity primary key,
  keyword text not null unique,
  search_count integer not null default 0,
  trend_status text,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  pref_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  preferred_tag text not null,
  constraint uq_user_preferences_user_tag unique (user_id, preferred_tag)
);

create table if not exists public.banners (
  banner_id bigint generated by default as identity primary key,
  image_url text not null,
  link_url text,
  display_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.notifications (
  notification_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  item_id bigint references public.items(item_id) on delete set null,
  notification_type text not null,
  title text not null,
  message text,
  payload jsonb,
  is_read boolean not null default false,
  send_status text not null default 'PENDING',
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  read_at timestamptz
);

create index if not exists idx_notifications_user_created
  on public.notifications (user_id, created_at desc);

create table if not exists public.notification_settings (
  setting_id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(user_id) on delete cascade,
  lowest_price_enabled boolean not null default true,
  sold_status_enabled boolean not null default true,
  new_item_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.keyword_alerts (
  keyword_alert_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  keyword text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint uq_keyword_alerts_user_keyword unique (user_id, keyword)
);

create table if not exists public.item_views (
  view_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  item_id bigint not null references public.items(item_id) on delete cascade,
  viewed_at timestamptz not null default now(),
  constraint uq_item_views_user_item unique (user_id, item_id)
);

create index if not exists idx_item_views_user_viewed
  on public.item_views (user_id, viewed_at desc);

create table if not exists public.chat_history (
  chat_id bigint generated by default as identity primary key,
  user_id uuid references public.users(user_id) on delete set null,
  user_message text,
  bot_response text,
  intent text,
  response_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_history_user_created
  on public.chat_history (user_id, created_at desc);

create table if not exists public.chat_faq (
  faq_id bigint generated by default as identity primary key,
  question_pattern text,
  answer_text text
);

create table if not exists public.recommended_items (
  recommend_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  item_id bigint not null references public.items(item_id) on delete cascade,
  score numeric,
  recommend_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_recommended_items_user_created
  on public.recommended_items (user_id, created_at desc);

alter table public.users enable row level security;
alter table public.items enable row level security;
alter table public.price_history enable row level security;
alter table public.wishlists enable row level security;
alter table public.search_logs enable row level security;
alter table public.search_rankings enable row level security;
alter table public.user_preferences enable row level security;
alter table public.banners enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_settings enable row level security;
alter table public.keyword_alerts enable row level security;
alter table public.item_views enable row level security;
alter table public.chat_history enable row level security;
alter table public.chat_faq enable row level security;
alter table public.recommended_items enable row level security;

drop policy if exists "users read own profile" on public.users;
create policy "users read own profile" on public.users
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own profile" on public.users;
create policy "users manage own profile" on public.users
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "public read items" on public.items;
create policy "public read items" on public.items
  for select using (true);

drop policy if exists "public read price history" on public.price_history;
create policy "public read price history" on public.price_history
  for select using (true);

drop policy if exists "public read rankings" on public.search_rankings;
create policy "public read rankings" on public.search_rankings
  for select using (true);

drop policy if exists "public read active banners" on public.banners;
create policy "public read active banners" on public.banners
  for select using (is_active = true);

drop policy if exists "public read chat faq" on public.chat_faq;
create policy "public read chat faq" on public.chat_faq
  for select using (true);

drop policy if exists "users read own wishlists" on public.wishlists;
create policy "users read own wishlists" on public.wishlists
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own wishlists" on public.wishlists;
create policy "users manage own wishlists" on public.wishlists
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users insert own search logs" on public.search_logs;
create policy "users insert own search logs" on public.search_logs
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "users read own search logs" on public.search_logs;
create policy "users read own search logs" on public.search_logs
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users read own preferences" on public.user_preferences;
create policy "users read own preferences" on public.user_preferences
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own preferences" on public.user_preferences;
create policy "users manage own preferences" on public.user_preferences
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own notification settings" on public.notification_settings;
create policy "users read own notification settings" on public.notification_settings
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own notification settings" on public.notification_settings;
create policy "users manage own notification settings" on public.notification_settings
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own keyword alerts" on public.keyword_alerts;
create policy "users read own keyword alerts" on public.keyword_alerts
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own keyword alerts" on public.keyword_alerts;
create policy "users manage own keyword alerts" on public.keyword_alerts
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own item views" on public.item_views;
create policy "users read own item views" on public.item_views
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users manage own item views" on public.item_views;
create policy "users manage own item views" on public.item_views
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "users read own chat history" on public.chat_history;
create policy "users read own chat history" on public.chat_history
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users insert own chat history" on public.chat_history;
create policy "users insert own chat history" on public.chat_history
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "users read own recommended items" on public.recommended_items;
create policy "users read own recommended items" on public.recommended_items
  for select to authenticated using ((select auth.uid()) = user_id);

-- 202606 service/search extension
-- 검색 이벤트, 매칭 근거, 가격 통계, 운영 콘텐츠 페이지를 보강합니다.

alter table public.wishlists
  add column if not exists is_sold_alert boolean not null default true;

alter table public.search_rankings
  add column if not exists platform_name text,
  add column if not exists period_start date,
  add column if not exists period_end date,
  add column if not exists calculated_at timestamptz not null default now();

alter table public.search_rankings
  drop constraint if exists search_rankings_keyword_key;

create index if not exists idx_search_rankings_period
  on public.search_rankings (period_start desc, period_end desc, search_count desc);

create table if not exists public.search_events (
  event_id bigint generated by default as identity primary key,
  user_id uuid references public.users(user_id) on delete set null,
  keyword text not null,
  platform_name text,
  item_id bigint references public.items(item_id) on delete set null,
  event_type text not null check (event_type in ('SEARCH', 'IMPRESSION', 'CLICK')),
  result_rank integer check (result_rank is null or result_rank > 0),
  relevance_score numeric,
  query_source text,
  created_at timestamptz not null default now()
);

create index if not exists idx_search_events_keyword_created
  on public.search_events (keyword, created_at desc);

create index if not exists idx_search_events_user_created
  on public.search_events (user_id, created_at desc);

create index if not exists idx_search_events_item_created
  on public.search_events (item_id, created_at desc);

create table if not exists public.item_search_matches (
  match_id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(item_id) on delete cascade,
  keyword text not null,
  canonical_name text,
  match_score numeric,
  match_reason text,
  match_source text not null default 'batch',
  matched_at timestamptz not null default now(),
  constraint uq_item_search_matches_item_keyword unique (item_id, keyword)
);

create index if not exists idx_item_search_matches_keyword_score
  on public.item_search_matches (keyword, match_score desc);

create table if not exists public.price_stats_daily (
  stat_id bigint generated by default as identity primary key,
  canonical_name text not null,
  platform_name text,
  stat_date date not null,
  lowest_price integer check (lowest_price is null or lowest_price >= 0),
  average_price numeric check (average_price is null or average_price >= 0),
  item_count integer not null default 0 check (item_count >= 0),
  calculated_at timestamptz not null default now(),
  constraint uq_price_stats_daily unique (canonical_name, platform_name, stat_date)
);

create index if not exists idx_price_stats_daily_name_date
  on public.price_stats_daily (canonical_name, stat_date desc);

create table if not exists public.content_pages (
  content_id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('NOTICE', 'TERMS', 'PRIVACY', 'FAQ', 'GUIDE')),
  title text not null,
  body text not null,
  version text,
  is_active boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_content_pages_type_active
  on public.content_pages (content_type, is_active, published_at desc);

alter table public.search_events enable row level security;
alter table public.item_search_matches enable row level security;
alter table public.price_stats_daily enable row level security;
alter table public.content_pages enable row level security;

drop policy if exists "users insert own search events" on public.search_events;
create policy "users insert own search events" on public.search_events
  for insert to authenticated
  with check ((user_id is null) or ((select auth.uid()) = user_id));

drop policy if exists "public read price stats daily" on public.price_stats_daily;
create policy "public read price stats daily" on public.price_stats_daily
  for select using (true);

drop policy if exists "public read active content pages" on public.content_pages;
create policy "public read active content pages" on public.content_pages
  for select using (is_active = true);
